/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3132",
        "tertiary-fixed-dim": "#c0c6db",
        "surface": "#f8f9fa",
        "on-secondary-fixed": "#121c28",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#930000",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#3e4755",
        "tertiary-container": "#5d6476",
        "inverse-primary": "#ffb4a8",
        "on-tertiary-fixed-variant": "#404758",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-container": "#dbe1f7",
        "primary-fixed-dim": "#ffb4a8",
        "surface-variant": "#e1e3e4",
        "secondary-fixed": "#d9e3f4",
        "background": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "outline-variant": "#e8bdb6",
        "on-error-container": "#93000a",
        "secondary": "#555f6d",
        "surface-dim": "#d9dadb",
        "on-primary-container": "#ffdad4",
        "on-error": "#ffffff",
        "on-surface": "#191c1d",
        "secondary-container": "#d6e0f1",
        "surface-tint": "#c00000",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffdad4",
        "on-surface-variant": "#5e3f3a",
        "on-background": "#191c1d",
        "error-container": "#ffdad6",
        "on-secondary-container": "#596372",
        "tertiary-fixed": "#dce2f7",
        "outline": "#926e69",
        "on-tertiary-fixed": "#141b2b",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed": "#410000",
        "surface-container": "#edeeef",
        "secondary-fixed-dim": "#bdc7d8",
        "primary-container": "#cc0000",
        "tertiary": "#454c5d",
        "primary": "#9e0000",
        "inverse-on-surface": "#f0f1f2",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "margin-desktop": "64px",
        "lg": "24px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "xs": "4px",
        "md": "16px",
        "xl": "40px",
        "sm": "8px",
        "section-lg": "120px",
        "section-md": "80px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.03em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-xl": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "display-xl": ["96px", {"lineHeight": "1", "letterSpacing": "-0.04em", "fontWeight": "800"}]
      },
      boxShadow: {
        'soft': '0 4px 12px rgba(17, 24, 39, 0.05)',
        'hover': '0 8px 24px rgba(17, 24, 39, 0.08)'
      }
    },
  },
  plugins: [],
}
